version: "3.8"
services:
    db:             
        image: mysql:8.0
        container_name: laravel_ecommerce_mysql_db
        restart: unless-stopped
        tty: true
        ports:
          - "3306:3306"

        volumes:
          - ./database/dbdata:/var/lib/mysql/
          # - ./mysql/my.cnf:/etc/mysql/my.cnf
        networks:
          - app-network

        environment:
          MYSQL_DATABASE: laravelEcommerce
          MYSQL_ROOT_PASSWORD: root
          SERVICE_TAGS: dev
          SERVICE_NAME: mysql

#Docker Networks
networks:
  app-network:
    driver: bridge
#Volumes
volumes:
  dbdata:
    driver: local
